name: raman
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - lightgbm=3.3.2
  - matplotlib=3.5.3
  - mlxtend=0.20.0
  - natsort=8.1.0
  - numpy=1.22.4
  - pandas=1.4.3
  - pybaselines=0.8.0
  - python=3.10.6
  - python-graphviz=0.20
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - seaborn=0.11.2
  - shap=0.41.0
  - tqdm=4.64.0
